### ISSUE TITLE
make Makefile ok for also ubuntu 22.04

### ISSUE THREAD

**Issue by dsir-minute** [itaru2622/docker-android-studio#5]
the original repo was designed for debian 11 (bulleyes) only.
If used as is on an ubuntu xfce 22.04, it fails.

The docker package in debian 11 is by default runnable without root,
This is not the case for docker on ubuntu 22.04, so a few instructions are added to circumvent that.

so here are the fixes for Makefile, you probably need to change esrlab to whatever user name you want to use: 
====================
# docker host directory for building android app

#top_dir=/tmp/android
top_dir=/home/eslabtcr/dockerAS

# UID and UserName for container
uid=1000
#uname=android
uname2023=eslabtcr_as

# directories in container (defaults of studio.sh)
sdk_dir=/home/${uname2023}/Android/Sdk
pj_dir=/home/${uname2023}/StudioProjects

# docker names, container and image
#container_name=android-studio
#img_name=itaru2622/android-studio:bullseye

container_name2023=raxy-AS

# android-studio version to use.
#ver_studio=2021.3.1.16
ver_studio2023=2022.2.1.18
img_name2023=raxy/android-studio:bullseye

# targes for ops. >>>>>>>>>>>>>>>>>>>>>>>>>>>>

#run: _prep
# docker run --name ${container_name} -it --rm --network host --privileged \
#   -v ${top_dir}/sdk:${sdk_dir} \
#   -v ${top_dir}/dot-android:/home/${uname}/.android \
#   -v ${top_dir}/dot-config:/home/${uname}/.config \
#   -v ${top_dir}/projects:${pj_dir} \
#   -e ANDROID_HOME=${sdk_dir} \
#        -e DISPLAY=${DISPLAY} \
#        -w ${pj_dir} \
# ${img_name} /bin/bash

#build:
# docker build --build-arg uid=${uid}  --build-arg uname=${uname} --build-arg ver_studio=${ver_studio} -t ${img_name} .

build:
docker build --build-arg uid=${uid}  --build-arg uname=${uname2023} --build-arg ver_studio=${ver_studio2023} -t ${img_name2023} .

exec:
docker exec -it -e DISPLAY=${DISPLAY} --user ${uname2023} ${container_name2023} /bin/bash

run: _prep
docker run --name ${container_name2023} -it --rm --network host --privileged \
  -v ${top_dir}/sdk:${sdk_dir} \
  -v ${top_dir}/dot-android:/home/${uname2023}/.android \
  -v ${top_dir}/dot-config:/home/${uname2023}/.config \
  -v ${top_dir}/projects:${pj_dir} \
  -e ANDROID_HOME=${sdk_dir} \
    -e DISPLAY=${DISPLAY} \
    -w ${pj_dir} \
${img_name2023} /bin/bash

runwith_daemon: _prep
docker run --name ${container_name2023} -itd --restart always --network host --privileged --user root \
  -v ${top_dir}/sdk:${sdk_dir} \
  -v ${top_dir}/dot-android:/home/${uname2023}/.android \
  -v ${top_dir}/dot-config:/home/${uname2023}/.config \
  -v ${top_dir}/projects:${pj_dir} \
  -e ANDROID_HOME=${sdk_dir} \
    -w ${pj_dir} \
${img_name2023} /sbin/init

docker exec -it -e DISPLAY=${DISPLAY} --user ${uname2023} ${container_name2023} /bin/bash

stop:
docker rm -f ${container_name2023}

_prep:
mkdir -p ${top_dir}/dot-android ${top_dir}/dot-config ${top_dir}/sdk ${top_dir}/projects
chmod a+w ${top_dir}/dot-android
chmod a+w ${top_dir}/dot-config
chmod a+w ${top_dir}/sdk
chmod a+w ${top_dir}/projects
xhost +

====================
so here are the fixes for Dockerfile : 
====================

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y curl git make wget screen bash-completion openssh-client tzdata unzip locales-all \
                   python3 python3-pip openjdk-11-jdk ibus-mozc
#RUN localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

ARG ver_studio
RUN (cd /tmp; \
     wget --progress=bar:force [https://dl.google.com/dl/android/studio/ide-zips/${ver_studio}/android-studio-${ver_studio}-linux.tar.gz](https://dl.google.com/dl/android/studio/ide-zips/$%7Bver_studio%7D/android-studio-$%7Bver_studio%7D-linux.tar.gz) -O android-studio.tgz ;\
     mkdir -p /opt/android-studio; \
     tar xvzf android-studio.tgz -C /opt ;\
    )

RUN dpkg --add-architecture i386
RUN apt update
RUN apt install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386 adb fastboot

ARG uid
ARG uname
RUN addgroup --system --gid ${uid} ${uname} ;\
    adduser  --system --gid ${uid} --uid ${uid} --shell /bin/bash ${uname} ;\
    echo "${uname}:${uname}" | chpasswd; \
    (cd /etc/skel; find . -type f -print | tar cf - -T - | tar xvf - -C/home/${uname} ) ;

RUN mkdir -p /home/${uname}/.android /home/${uname}/.config /home/${uname}/AndroidStudioProjects; \
    chown -R ${uname}:${uname} /opt/android-studio /home/${uname}

RUN rm -f /tmp/android-studio.tgz

VOLUME /home/${uname}/.android /home/${uname}/.config /home/${uname}/AndroidStudioProjects
ENV PATH=${PATH}:/opt/android-studio/bin
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV STUDIO_JDK=${JAVA_HOME}
ENV DEBIAN_FRONTEND=
#RUN dpkg --remove-architecture i386; apt update
RUN apt-get install -y mousepad
USER ${uname}
WORKDIR /home/${uname}/AndroidStudioProjects

**Comment by dbolser** [comment]
Can you make a PR please?

**Comment by itaru2622** [comment]
@dsir-minute @dbolser Thank you for your comment, and sorry for too late response.

I have been away from android development for a long time.
I updated my Dockerfile, Makefile to support additional app with current OS,  android-studio, JDK.

now, you can change baseOS image, and android-studio version, JDK version via Makefile.
you can edit your Makefile freely.
moreover,  even without editing,  you can involve  your favorite combinations directly like below:

```bash
make build img_base=ubuntu:22.04 uname=anyname uid=yyy extra_app=mousepad
```

**Comment by dbolser** [comment]
Thanks!
